base_url = "https://blindinlights-cc.github.io"
title = "Blindinlights' Blog"
theme="zola-theme-terminimal"
compile_sass = true
taxonomies = [
    {name = "tags"}
]
[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]
accent_color = "blue"
background_color = "blue"
logo_text = "Blidninlights"
menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "about me", url = "$BASE_URL/about"},
    {name = "github", url = "https://github.com/Blindinlights-cc", newtab = true},
]
enable_post_view_navigation = true
post_view_navigation_prompt = "Thanks for reading! Read other posts?"
use_full_hack_font = false
page_titles = "main_only"
